name: Run Kaggle Notebook Twice Daily

on:
  schedule:
    - cron: '0 8 * * *'   # 8 AM UTC
    - cron: '0 15 * * *'  # 3 PM UTC
  workflow_dispatch:      # Manual trigger button in GitHub Actions

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install kaggle jupyter nbconvert ipykernel

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Verify notebook exists
      run: |
        ls -lh github-automated-template.ipynb || echo "Input notebook not found"

    - name: Run notebook as script
      run: |
        jupyter nbconvert --to notebook --execute github-automated-template.ipynb --output output.ipynb --debug 2>&1 | tee nbconvert.log
        ls -lh output.ipynb || echo "Output file not found"
        cat nbconvert.log || echo "No log file generated"

    - name: Upload notebook output
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: notebook-output
        path: output.ipynb
        if-no-files-found: warn

    - name: Upload debug log
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: nbconvert-log
        path: nbconvert.log
        if-no-files-found: warn
