name: Run Kaggle Notebook Twice Daily

on:
  schedule:
    - cron: '0 16 * * *'   # 8 AM Pacific
    - cron: '0 23 * * *'   # 3 PM Pacific
  workflow_dispatch:

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install kaggle nbconvert ipykernel

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: List files for debugging
      run: ls -lhR .github/workflows/

    - name: Run notebook
      id: run_notebook
      run: |
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=300 \
          .github/workflows/github-automated-tempalert.ipynb

    - name: Retry if notebook failed
      if: failure()
      run: |
        echo "⏳ Waiting 5 minutes before retry..."
        sleep 300

        echo "🔁 Retrying notebook execution..."
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=300 \
          .github/workflows/github-automated-tempalert.ipynb
